spring.application.name=MessMate
server.port=${PORT:8080}
spring.datasource.url=${DB_DEV_URL}
spring.datasource.username=${DB_DEV_USERNAME}
spring.datasource.password=${DB_DEV_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=${JWT_SECRET_KEY}

deploy.env = development

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# spring.config.import=optional:file:.env