spring.application.name=MessMate
spring.datasource.url=${DB_DEV_URL}
spring.datasource.username=${DB_DEV_USERNAME}
spring.datasource.password=${DB_DEV_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=${JWT_SECRET_KEY}

deploy.env = development

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Resend email config
resend.api-key=${RESEND_API_KEY}
resend.from=${EMAIL_FROM}
app.backend-url=${BACKEND_URL:http://localhost:8080}