spring.application.name=MessMate
spring.datasource.url=${DB_PROD_URL}
spring.datasource.username=${DB_PROD_USERNAME}
spring.datasource.password=${DB_PROD_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secretKey=${JWT_SECRET_KEY}

deploy.env = production

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#set time zone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# Resend email config
resend.api-key=${RESEND_API_KEY}
resend.from=${EMAIL_FROM}